# -*- coding: utf-8 -*-
"""YouTube Lyrics Downloader

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yu_meg5fEINi9_L1Pv7qTwipP_5UlMeG
"""

import streamlit as st
import re
from youtube_transcript_api import YouTubeTranscriptApi, NoTranscriptFound, TranscriptsDisabled
from deep_translator import GoogleTranslator

# -------- Helpers --------
def extract_video_id(url: str) -> str:
    """Extract YouTube video ID from URL"""
    match = re.search(r"(?:v=|youtu\.be/)([a-zA-Z0-9_-]{11})", url)
    return match.group(1) if match else None

def fetch_transcript(video_id: str):
    """Fetch transcript if available"""
    try:
        # auto fetch any available transcript
        transcript = YouTubeTranscriptApi.list_transcripts(video_id)
        # Prefer English, fallback to first available
        try:
            return transcript.find_transcript(['en']).fetch()
        except:
            return transcript.find_transcript(transcript._manually_created_transcripts.keys() 
                                              or transcript._generated_transcripts.keys()).fetch()
    except (NoTranscriptFound, TranscriptsDisabled):
        return None
    except Exception as e:
        st.error(f"Unexpected error: {e}")
        return None

def transcript_to_text(transcript):
    """Join transcript into plain text lyrics"""
    return " ".join([entry["text"] for entry in transcript])

def translate_text(text, dest_lang="te"):
    """Translate text into Telugu using deep-translator"""
    return GoogleTranslator(source="auto", target=dest_lang).translate(text)

# -------- Streamlit App --------
st.set_page_config(page_title="YouTube → Telugu Lyrics BOT", layout="centered")
st.title("🎶 YouTube Song to Telugu Lyrics BOT")

youtube_url = st.text_input("Enter YouTube Song URL:")

if youtube_url:
    video_id = extract_video_id(youtube_url)

    if not video_id:
        st.error("❌ Invalid YouTube URL. Please check and try again.")
    else:
        st.info("⏳ Fetching transcript...")
        transcript = fetch_transcript(video_id)

        if not transcript:
            st.error("❌ No captions available for this video (might be instrumental/live).")
        else:
            english_text = transcript_to_text(transcript)
            st.subheader("Extracted Lyrics (Original):")
            st.text_area("Original Captions", english_text, height=200)

            # Translate
            st.info("⏳ Translating to Telugu...")
            telugu_text = translate_text(english_text, dest_lang="te")

            st.subheader("🎵 Telugu Lyrics:")
            st.text_area("Telugu Lyrics", telugu_text, height=200)

            # Download Button
            st.download_button(
                label="⬇️ Download Telugu Lyrics",
                data=telugu_text.encode("utf-8"),
                file_name="telugu_lyrics.txt",
                mime="text/plain"
            )
